source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'OHHTTPStubs.xcodeproj'
inhibit_all_warnings!

def pod_afnetworking
    pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git', :branch => '3_0_0_branch'
end

target 'OHHTTPStubs iOS Lib Tests' do
    platform :ios, '7.0'
    pod_afnetworking
end

target 'OHHTTPStubs iOS Fmk Tests' do
    platform :ios, '8.0'
    pod_afnetworking
end

target 'OHHTTPStubs Mac Tests' do
    platform :osx, '10.9'
    pod_afnetworking
end

target 'OHHTTPStubs tvOS Fmk Tests' do
    platform :tvos, '9.0'
    pod_afnetworking
end
