source 'https://github.com/CocoaPods/Specs.git'

project 'OHHTTPStubsDemo.xcodeproj'
platform :ios, '11.0'
use_frameworks!

target 'OHHTTPStubsDemo' do
  pod 'OHHTTPStubs', :path => '../..'
  pod 'OHHTTPStubs/Swift', :path => '../..'
end
