source 'https://cdn.cocoapods.org/'

project 'OHHTTPStubsDemo.xcodeproj'
platform :ios, '12.0'
use_frameworks!

target 'OHHTTPStubsDemo' do
  pod 'OHHTTPStubs', :path => '../..'
  pod 'OHHTTPStubs/Swift', :path => '../..'
end
