source 'https://github.com/CocoaPods/Specs.git'
xcodeproj 'OHHTTPStubsDemo.xcodeproj'
platform :ios, '6.0'

pod 'OHHTTPStubs', :git => 'https://github.com/AliSoftware/OHHTTPStubs.git', :branch => 'master'